### ISSUE TITLE
Typos in chap. 1, page 24 of the PDF release

### ISSUE THREAD

**Issue by maxhgerlach** [pycabook/pycabook#1]
These caught my attention in the paragraph before "Step 3 - Adding multiple numbers":

1. It should be "this being an introduction", not "being this an introduction"
2. The last sentence in that paragraph does not end properly.

Thanks for sharing the book for free!

**Comment by lgiordani** [comment]
Oh my, it's true, one never checks things enough... Thanks! I'll fix them ASAP
