### ISSUE TITLE
TDD Intro, Step 9, requirements breakdown typo

### ISSUE THREAD

**Issue by grantmoore3d** [pycabook/pycabook#11]
Spotted a small typo in the requirements breakdown from "Step 9 - A more complex set of requirements" in the introduction to TDD.

The lower threshold is not included in the comparison, i.e. avg([2, 5, 12, 98], ut=5) ==
avg([5, 12, 98])

**The lower threshold is not included in the comparison, i.e. avg([2, 5, 12, 98], lt=5) ==
avg([5, 12, 98])**

**Comment by lgiordani** [comment]
Ouch! Thanks, I fixed it and I will release a new version of the book with the correction
