### ISSUE TITLE
TDD Intro, Step 9.7 - Empty list after applying the thresholds

### ISSUE THREAD

**Issue by faustgertz** [pycabook/pycabook#13]
I noticed your solution for `avg()` at 'step-9-7-empty-list-after-thresholds' fails for zero-valued thresholds. For example: 

```
def test_avg_manages_zero_value_lower_outlier():
    Calc().avg([-1, 0, 1], lt=0) == .5
```

I think you need to check for  `is not None` or `not <var> is None` instead of just for `False`.

```
    def avg(self, it, lt=None, ut=None):
        _it = it[:]
        if lt is not None:
            _it = [x for x in _it if x >= lt]
        if ut is not None:
            _it = [x for x in _it if x <= ut]
        if not len(_it):
            return 0
        return sum(_it) / len(_it)
```

**Comment by lgiordani** [comment]
Thanks Faust, I need a bit of time to mull this over. I'd like to use it as an example of TDD in practice. I'll close it as soon as I include it in the book. Many thanks!

**Comment by lgiordani** [comment]
@faustgertz did you have a chance to double-check it?

**Comment by IrishPrime** [comment]
I noticed the same thing and just ran his test (with the addition of `pytest.approx` and an `assert`).

```
========================================== FAILURES ==========================================
_________________________ test_avg_manages_zero_value_lower_outlier __________________________

    def test_avg_manages_zero_value_lower_outlier():
        c = Calc()
    
        res = c.avg([-1, 0, 1], lt=0)
    
>       assert res == pytest.approx(.5)
E       assert 0.0 == 0.5 ± 5.0e-07
E        +  where 0.5 ± 5.0e-07 = <function approx at 0x7f79d29ed0d0>(0.5)
E        +    where <function approx at 0x7f79d29ed0d0> = pytest.approx

tests/test_calc.py:118: AssertionError
============================ 1 failed, 18 passed in 0.07 seconds =============================
```

**Comment by faustgertz** [comment]
I forgot the word `assert` in the test I included above. Try:

```
def test_avg_manages_zero_value_lower_outlier():
    assert Calc().avg([-1, 0, 1], lt=0) == .5
```

I get:

```
======================== FAILURES ========================
_______ test_avg_manages_zero_value_lower_outlier ________

    def test_avg_manages_zero_value_lower_outlier():
>       assert Calc().avg([-1, 0, 1], lt=0) == .5
E       assert 0.0 == 0.5
E         -0.0
E         +0.5

tests/test_calc.py:89: AssertionError
========== 1 failed, 18 passed in 0.12 seconds ===========

```

**Comment by lgiordani** [comment]
Thanks both, I'll work on it as soon as possible, there is something fishy going on :fish: :joy_cat:

**Comment by IrishPrime** [comment]
Nothing fishy about it.

```python
if lt:
    _it = [x for x in _it if x >= lt]
```

This is fine if `lt` evaluates to a truthy value, but `0` is falsey and so the statement is skipped. You just have to make sure the value is set (`not None`) rather than truthy. The suggested fix works fine.

You could actually use this as a great example in the book about test design and exercising edge/corner cases.

**Comment by lgiordani** [comment]
The "fishy" part was that I couldn't replicate it :joy_cat: You are right that was my initial plan for this issue, and I will do as you said in the book

**Comment by lgiordani** [comment]
^ Sorry, I'm working on it and I'm clicking random buttons :see_no_evil:

**Comment by lgiordani** [comment]
I'm about to publish version 1.0.8 which contains this fix. Thank you both! The most important contribution to the book so far!
