### ISSUE TITLE
About the Book - Missing verb when describing TDD

### ISSUE THREAD

**Issue by IrishPrime** [pycabook/pycabook#20]
In the "About the Book" section, the first sentence describing the benefits of TDD is missing a verb.

> The first part is about Test-driven Development (TDD), a programming technique that will help you \<BLANK\> more reliable and easily modifiable software.

"Develop," "write," or "create" all seem like good options to add here.

**Comment by lgiordani** [comment]
It looks like the hook failed and didn't close the issue. Doing it manually. Thanks again

**Comment by IrishPrime** [comment]
Happy to help. Enjoying the read, figured it was the least I could do.
