### ISSUE TITLE
Inconsistent `test_add_many_numbers()` and `test_mul_many_numbers()`

### ISSUE THREAD

**Issue by wzel** [pycabook/pycabook#26]
Unlike preceding tests pertaining to the behavior of the `Calc` class, these two do not perform the instantiation and calculation assignment  to `res`. This is confusing.
I'm submitting the issue following the suggestion of @lgiordani.

**Comment by lgiordani** [comment]
I'm sorry I forgot to address this issue. I'm not ignoring it, I will work on it soon.

**Comment by lgiordani** [comment]
Hi @wzel! So, in the second edition of the book I will get rid of the part on TDD, which has been published on my blog as a series of posts. You can find it here https://www.thedigitalcatonline.com/blog/2020/09/10/tdd-in-python-with-pytest-part-1/. The code has been reworked and I also solved this issue.

I will close this as soon as the new edition is out, thanks a lot for mentioning it!
