### ISSUE TITLE
Bad and un-Pythonic naming

### ISSUE THREAD

**Issue by valorien** [pycabook/pycabook#28]
In Chapter 1, "Step 1 - Adding two numbers", first paragraph:
`from calc.calc import Calc`? seriously?
The project itself is called "calc" and now you have a folder called "calc" with a file called "calc" with a class called "Calc" with a capital c.
I know you're not trying to teach people Python but there's no need to over-confuse readers, and for absolutely no good reason. These are terrible names and even more so when you consider how uncomprehensible the import statements are. Here's how importing the Calc class from outside the project would look like: `from calc.calc.calc import Calc`. That's just bad.

Also in the same paragraph:
```
c = Calc()

res = c.add(4, 5)
```
How hard is it to write `calculator = Calc()` and `result = calculator.add(4, 5)`?
Heaven forbid having meaningful variable names in our code.

**Comment by lgiordani** [comment]
Thank you for taking the time to submit an issue. I think you are right and that I could have chosen a better naming. I'm pretty concerned myself with having proper variable names, so I can't but agree. As for the un-Pythonic, the `datetime` module of the standard lib contains the `datetime` class, so as you can see even the core of the language has its quirks. =)

An advice, if you want to keep contributing to Open Source. Pay attention to how you phrase issues, suggestions, and remarks, especially when they are written. There is a gentler way to show people that what they did is not the best they could have done, in particular when things are free. Politeness is cheap and makes the other more wiling to accept criticism or correction.

That said, as I think you raised a proper issue, I will definitely consider clarifying the code for the next version of the book.

Thank you again for submitting it.

**Comment by valorien** [comment]
@lgiordani Apologies. You're absolutely right and I'll take this to heart.
Thank you for writing this book and for addressing the issue.
I hope to contribute more feedback soon, and I'll do so in a polite and friendly manner from now on.

**Comment by lgiordani** [comment]
Thank you. I'm looking forward to receiving more feedback!

**Comment by lgiordani** [comment]
Hi! Apologies for the delay. In the second edition of the book I will remove the section on TDD, as I will consider it a prerequisite. I'm moving that section to my blog, so this week I will publish it split in a series of posts. I reworked the example following your advice, I hope the new version is better. You can find the repository at https://github.com/lgiordani/simple_calculator and the first post at https://www.thedigitalcatonline.com/blog/2020/09/10/tdd-in-python-with-pytest-part-1/

Let me know what you think. Thanks for your feedback!

**Comment by lgiordani** [comment]
Hey @valorien did you have any chance to have a look at the posts I published? What do you think?
