### ISSUE TITLE
Question: Why create Use Case classes with one method instead of functions?

### ISSUE THREAD

**Issue by lorey** [pycabook/pycabook#29]
Found your book while looking for best-practices around structuring python projects. Have been reading it for the last few days and it's been a great pleasure! Thank you so much <3

My question is:
In part 2, when building the RoomListUseCase, [a class](https://github.com/pycabook/rentomatic/blob/master/rentomatic/use_cases/room_list_use_case.py#L4) that only includes `__init__(repo)` and `execute()` is created. I would have used a plain function and I think many others might think about that too. I'm sure there's a reason for it and maybe it makes sense to explain this a little bit, because at least for me the choice is not obvious.

Would you mind to elaborate on that?

**Comment by AdamJel** [comment]
I support this question. I believe, I've seen an explanation in this very quoted [talk](https://www.youtube.com/watch?v=o9pEzgHorH0), where is specifically advised, if there is just one method in your class, make it a function instead.

So what is the reasoning here, please?

**Comment by lgiordani** [comment]
Hi both, apologies for not answering, I completely missed the notification. I will think about it, watch the talk, and then come back to you. Thanks!

**Comment by lorey** [comment]
Thanks for following up, highly appreciated! When I implemented the use cases for myself, I found that if I want to keep things lean, it makes sense to separate dependencies from actual parameters. So you can construct first and execute somewhere else later.
