### ISSUE TITLE
fix: typo?

### ISSUE THREAD

**Issue by AdamJel** [pycabook/pycabook#30]
Hi,

first of all, let me thank you for you - writing the book and making it public and open-source. I just started reading it to broaden my knowledge base.

I want to ask about a possible typo in chapter_02_about_the_book.md, line 65: `Apple ][` section. I consider it a typo, since I don't know a meaning of the "][" following Apple. But if there is some, perhaps archaic, meaning of that bracket pair, please, I will gladly learn something new.

Thank you :)

**Comment by lgiordani** [comment]
Hi! Thanks for the message and for reading the book! No that is not a typo, actually the computer called Apple II (https://en.wikipedia.org/wiki/Apple_II) was usually written as Apple ][. It's just a nice memory I'm fond of, I didn't want to confuse readers :wink:

**Comment by AdamJel** [comment]
Oh, I knew there could be something about it! It's unfortunately not even rendered well. See pic from downloaded pdf:

![apple_brackets](https://user-images.githubusercontent.com/33990009/87532896-1c458900-c694-11ea-9249-2746db48551c.jpg)

Do you see, how slightly misaligned they are?

However, thank you for the information, I in deed learned something new :)
