### ISSUE TITLE
Minor corrections

### ISSUE THREAD

**Issue by gnatale** [pycabook/pycabook#32]
Thanks for writing such a useful and clearly-written book!

Just wanted to share with you a few minor points that could be corrected/improved. I downloaded the book from the platform scribd and I am not sure if the page numbers match those in the latest version.

p. 128:

when calling: http://localhost:5000/rooms?filter_price__lt=50

the value 50 is read as a string by the backend code (at least this happened to me using Firefox on my Mac Air). This causes an error in the file memrepo.py at the line:

result = [r for r in result if r.price < filters['price__lt']]

because the operator "<" cannot be used to compare an integer and a string.  

p. 144: 

the sentence “that a database run in a container will lose all the data when the container is stopped.” is a bit inaccurate/incomplete. To preserve data it is possible to use docker volumes and mount them on the containers.   

p. 143:

assert len(repo_romos) == 1 

typo: repo_romos -> repo_rooms

p 135: 

docker_compose_file function

sharing the port 5432 with the host can cause problems if there is another program already using that port on the host (for example if one has already a running postgresql server on the host). It might be worth to add a warning that the port 5432 should be free on the host or that one can use a different port in principle.

Thanks!

**Comment by lgiordani** [comment]
@gnatale Thanks! I can't believe that after 2 years and so many corrections sent by readers there are still issues :sweat_smile: I will review the problems you pointed out and publish an updated version as soon as possible. Thanks again!

**Comment by lgiordani** [comment]
This has been solved in version 2.1.0. Thanks!
