### ISSUE TITLE
Namespace conflict on second edition

### ISSUE THREAD

**Issue by staticdev** [pycabook/pycabook#36]
Hi @lgiordani!

I saw that you stopped having a folder `rentomatic.request_objects.room_list_request_object` to have 
`rentomatic.requests.room_list`.

I like the naming, but unfortunately, I wouldn't go that path, since it will conflict with the famous `requests` library (if used by any dependency in the tree) having it as part of the structure of your clean architecture template.

Merry Xmas!

**Comment by lgiordani** [comment]
Thanks for the advice. I wasn't sure about that, I will reconsider and
double check what I did. Merry Christmas to you as well!

**Comment by lgiordani** [comment]
Hey @staticdev I double-checked and the naming doesn't clash with `requests` as it is correctly namespaced under `rentomatic` (see for example `cli.py` or `tests/requests/test_room_list.py`). Clearly, this being an example, I'm not suggesting everybody should go this path, so I might add a note about name clashing at some point in the book. Thanks for spotting that possible issue!

**Comment by staticdev** [comment]
@lgiordani I have a real app inspired on your book.. if you just clone it and try to run it after renaming the folder `src/request_objects` to `requests`substituting all `import git_portfolio.request_objects.` with `import git_portfolio.requests.` and run `__main__.py config init`. You will get the error:

```
Traceback (most recent call last):
  File "/home/static/.pyenv/versions/3.9.0/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/static/.pyenv/versions/3.9.0/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/static/.vscode/extensions/ms-python.python-2020.12.424452561/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/home/static/.vscode/extensions/ms-python.python-2020.12.424452561/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/home/static/.vscode/extensions/ms-python.python-2020.12.424452561/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/home/static/.pyenv/versions/3.9.0/lib/python3.9/runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/static/.pyenv/versions/3.9.0/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/static/.pyenv/versions/3.9.0/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/static/workspace/git-portfolio/src/git_portfolio/__main__.py", line 15, in <module>
    import git_portfolio.github_service as ghs
  File "/home/static/workspace/git-portfolio/src/git_portfolio/github_service.py", line 7, in <module>
    import github3
  File "/home/static/.cache/pypoetry/virtualenvs/git-portfolio-YCsIKJvU-py3.9/lib/python3.9/site-packages/github3/__init__.py", line 24, in <module>
    from .api import (
  File "/home/static/.cache/pypoetry/virtualenvs/git-portfolio-YCsIKJvU-py3.9/lib/python3.9/site-packages/github3/api.py", line 13, in <module>
    from .github import GitHub, GitHubEnterprise
  File "/home/static/.cache/pypoetry/virtualenvs/git-portfolio-YCsIKJvU-py3.9/lib/python3.9/site-packages/github3/github.py", line 10, in <module>
    from . import apps
  File "/home/static/.cache/pypoetry/virtualenvs/git-portfolio-YCsIKJvU-py3.9/lib/python3.9/site-packages/github3/apps.py", line 10, in <module>
    from . import models
  File "/home/static/.cache/pypoetry/virtualenvs/git-portfolio-YCsIKJvU-py3.9/lib/python3.9/site-packages/github3/models.py", line 10, in <module>
    import requests.compat
ModuleNotFoundError: No module named 'requests.compat'
``` 

If you rename it back to `request_objects`, no error anymore =)

**Comment by lgiordani** [comment]
I'll have a look asap! Thanks

**Comment by lgiordani** [comment]
Thiago, it's pretty complicated to understand how to run that project. There is a directory `src/git_portfolio`, but when I run `python3 __main__.py config init` I get

```
Traceback (most recent call last):
  File "__main__.py", line 12, in <module>
    import git_portfolio.config_manager as cm
ModuleNotFoundError: No module named 'git_portfolio'
```

Not really sure how you run it.
However, looking at the error above, it looks like renaming you overrode something used by `github3/models.py`. I understand that `request` is  a common name, but if you `import git_portfolio.requests` I can't see how this could override any `import requests` in other parts of the code. Otherwise every time you call a file `path.py` you should override `os.path`, and so on.

Can you please clarify? Thanks

**Comment by staticdev** [comment]
Sorry for my bad instructions!

But first, you are correct.. github3/models.py have `import requests` as you can see [here](https://github.com/sigmavirus24/github3.py/blob/master/src/github3/models.py).

Basically this project runs on poetry:
* **If you have poetry** should be straightforward `poetry install` and `poetry run gitp config init` (or even `poetry shell` and `gitp config init`).
* **If you don't have poetry**, you can just `pip install -r requirements.txt` with this requirements generated by poetry:

```
ansicon==1.89.0; platform_system == "Windows"
blessed==1.17.6
certifi==2020.6.20; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.5.0"
cffi==1.14.3; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.5.0"
chardet==3.0.4; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.5.0"
click==7.1.2; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.5.0")
cryptography==3.2.1; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.5.0"
github3.py==1.3.0
idna==2.10; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.5.0"
inquirer==2.7.0
jinxed==1.0.1; platform_system == "Windows"
jwcrypto==0.8
pycparser==2.20; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.5.0"
python-dateutil==2.8.1; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.3.0"
python-editor==1.0.4
pyyaml==5.3.1; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.5.0")
readchar==2.0.1
requests==2.24.0; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.5.0"
six==1.15.0; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.5.0"
uritemplate==3.0.1; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.4.0"
urllib3==1.25.11; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.5.0" and python_version < "4"
wcwidth==0.2.5
```

For debugging I usually use a launch.json on VSCode:

```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "args": ["config", "init"],
            "cwd": "${workspaceFolder}/.."
        }
    ]
}
```

**Comment by lgiordani** [comment]
Look, I'm sorry, but I can't install a keyring and get a GH token to debug this, I'm already swamped with the book and other projects. As I explained, I can't figure how you can possibly override `import requests` and `import requests.compat` with a local module, unless you specifically import it in the global namespace with the name `requests`, but this is not what I do.

In Python there is nothing that forbids calling local modules like other modules, otherwise nowadays it would be impossible to release anything. Look further into your code, I'm sure there is something wrong with your imports.

**Comment by lgiordani** [comment]
@staticdev I tried other times to replicate this but I didn't manage. I'm sorry to close an unsolved issue but I don't know what to do here. Feel free to open it again if you have more information or a clue about what's going on. Apologies!
