### ISSUE TITLE
Typo p.21 "RObert Martin"

### ISSUE THREAD

**Issue by JakWai01** [pycabook/pycabook#44]
I hope this mistake was not intended as a joke (I did not get it then :D). Thanks for this great book. I also checked out your blog and I really enjoyed it's design. Thank you for your work!

**Comment by lgiordani** [comment]
Thank you for reading the book and the blog!
Many people already sent me the notification for that typo (not a joke at all), and I thought I already fixed it. Apparently I did it only in the HTML version and not in the PDF. Thanks, I'll fix it asap

**Comment by lgiordani** [comment]
This has been solved in version 2.1.0. Thanks!
