### ISSUE TITLE
Typo "applicaton/config.py" missing i

### ISSUE THREAD

**Issue by mathisheeren** [pycabook/pycabook#49]
I think I found two typos on page 43 in the book.

1. In the text above the code block: 
    - "the file applicaton/config.py that contains"  
2. In the path to the file:
    - "applicaton/config.py"
 
I don't know exactly in which file it has to be changed so I've picked something out maybe it will help😉.
- pycabook/src/06_Chapter_04_Add_a_web_application.mau on line 50 and 52.
- pycabook/src/06_Chapter_04_Add_a_web_application.adoc on line 46 and 48.

Thank you for your book I am reading it right now and have already learned an incredible amount 👌👏.

**Comment by lgiordani** [comment]
This has been solved in version 2.1.0. Thanks!
