### ISSUE TITLE
Missing valid test on price__eq with string

### ISSUE THREAD

**Issue by ivanovmg** [pycabook/pycabook#55]
I noticed that ``test_repository_list_price_as_strings`` in ``tests/repository/test_memrepo.py``
does not cover the case ``price__eq`` with string value properly (section 5.7.2).
Currently it simply goes through the code, but the result is not compared with the benchmark.

For example, I managed to remove conversion to ``int`` in ``MemRepo``, inside ``price__eq`` if statement.
The tests still pass, which is unexpected.

The problem here is that that the comparison between ``int`` is ``str`` can be run without failure, but the result will be ``False``.

It is possible to parametrize tests for all operators with ints and strings.
Just like this:

``` python
@pytest.mark.parametrize('price', [60, '60'])
def test_repository_list_with_price_equal_filter(room_dicts, price):
    repo = MemRepo(room_dicts)
    result = repo.list(filters={"price__eq": price})

    room_dict = {
        "code": "913694c6-435a-4366-ba0d-da5334a611b2",
        "size": 56,
        "price": 60,
        "longitude": 0.27891577,
        "latitude": 51.45994069,
    }
    expected = [Room.from_dict(room_dict)]

    assert result == expected
```

Note that the core of this test is not the same as in the book.

**Comment by lgiordani** [comment]
This has been solved in version 2.1.0. Thanks!
