### ISSUE TITLE
Something wrong with footnotes

### ISSUE THREAD

**Issue by StrontyD** [pycabook/pycabook#61]
Hi, I am only at the first page of chapter one and I have read the same footnote about the simplest mock you had to write three times I think, with different footnote numbers but the same test each time each time. I know nothing about you publishing process but something isn't happy there. Cheers Steve

**Comment by StrontyD** [comment]
Well text not test. Doh!

**Comment by lgiordani** [comment]
Thanks for the feedback Steve, and sorry for the mistake. I can confirm the PDF footnotes are wrong, I will fix this as soon as possible. In the meantime you can see the proper footnotes in the HTML version of the book at https://www.thedigitalcatbooks.com/
Thanks again!

**Comment by StrontyD** [comment]
Absolutely fine, it hasn't bothered me, just letting you know. Thanks for your generous efforts, I know little about python and this may be a strange place to start but I seem to be keeping up.

Regards Steve

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by lgiordani** [comment]
Steve, I think I fixed the mistake in my publishing chain. I just generated a new version of the book (2.1.2), can you please have a look and confirm the issue is solved? Thanks! Happy learning.

**Comment by StrontyD** [comment]
Hi Leonardo

Yes from a quick check it seems to be fixed. Thanks.

Regards

Steve

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by lgiordani** [comment]
Thank you for spotting it!
