### ISSUE TITLE
Chapter 7 Systemfootnote

### ISSUE THREAD

**Issue by isparks** [pycabook/pycabook#64]
Chapter 7 there's a "systemfootnote" marker that looks like its not being properly processed and instead just runs in with the code.

Just after the code example here: https://www.thedigitalcatbooks.com/pycabook-chapter-07/#the-mongodb-repository

....similarity between the filters of the Rent-o-matic project and the ones of the MongoDB **systemfootnote:[The similitude between the two systems is not accidental, as I was studying MongoDB at the time I wrote the first article about clean architectures, so I was obviously influenced by it.].**

Otherwise, enjoying the book, thanks.

**Comment by lgiordani** [comment]
Ouch! A leftover of the old version that was written in Markua!
Thanks for spotting it, I will fix it. And thanks for reading the book!

**Comment by lgiordani** [comment]
Hi @isparks, yesterday I published a version of the book where this typo has been fixed. I will fix the online version as soon as I also fix the toolchain I use for that, but at least the PDF is correct now. I recorded your contribution in the Changelog. Thanks!
