### ISSUE TITLE
363357

### ISSUE THREAD

**Issue by Robert-at-GE** [pycabook/pycabook#65]
### Minor Typographical Error
Under "Typographic conventions" on page 7, it says that Code blocks *don't* contain line numbers. But, that seems to be an error because line numbers are clearly visible in the example code block.   I've highlighted the phrase in the attached screen clip:
![code-blocks-line-numbers](https://user-images.githubusercontent.com/18406505/199119807-fcf2405e-d9c4-4ed9-824e-11fbb06b3528.jpg)

**Comment by lgiordani** [comment]
Oh, thank you! Yeah, I turned them on and forgot to remove the mention in the preface. I will fix it! Thanks!

**Comment by lgiordani** [comment]
Hey @Robert-at-GE thanks for the contribution, I fixed this in the last version of the book that I published yesterday. Your contribution has been recorded in the Changelog. Thanks!
